/** @jsx React.DOM */

var Example = React.createClass({
  handleCancel: function() { this.refs.modal.close(); },

  render: function() {
    var modal = null;
    modal = (
      <BootstrapEditor
        ref="modal"
        confirm="OK"
        cancel="Cancel"
        delete="Delete"
        onCancel={this.handleCancel}
        onConfirm={this.closeModal}
        title="Hello, Bootstrap!">
        <form role="form" className="form-horizontal">
          <span className="help-block">This is a React component powered by jQuery and Bootstrap!</span>
          <div className="form-group">
            <label htmlFor="inputEmail3" className="col-sm-2 control-label">Email</label>
            <div className="col-sm-10">
              <input type="email" className="form-control" id="inputEmail3" placeholder="Email"/>
            </div>
          </div>
          <div className="form-group">
            <label htmlFor="inputPassword3" className="col-sm-2 control-label">Password</label>
            <div className="col-sm-10">
              <input type="password" className="form-control" id="inputPassword3" placeholder="Password"/>
            </div>
          </div>        
        </form>
      </BootstrapEditor>
    );

    return (
      <div className="example">
        {modal}
        <BootstrapButton onClick={this.openModal} text="Demo modal (generated by React)" icon="glyphicon-star" size="btn-lg" />
      </div>
    );
  },
  openModal: function() { this.refs.modal.open(); },
  closeModal: function() { this.refs.modal.close(); }
});

var trg = $("#btnStar");
var bdy = $("#content");

//React.renderComponent(<ModalTrigger trigger={trg} header="hdr" body={bdy} footer="ftr" />,  document.getElementById('example2'));

React.renderComponent(<Example />,  document.getElementById('example2'));
